### PR TITLE
Return result of waitForAngularRequestsToFinish

### LINKED ISSUE #97: Return result of waitForAngularRequestsToFinish
It would be great if the result of the waitForAngularRequestsToFinish could be returned.

In case there is an issue with the root selector this can return some more meaningful error messages.

### PR DESCRIPTION
**Pull request by tarioch**
Fixes #97

### CODE REVIEW

**Comment by paul-hammant** [comment]
Nice, but can we have a test and documentation for that?

**Comment by tarioch** [comment]
Thanks for the comments, I added a test case and some doc in the readme.

**Comment by paul-hammant** [comment]
Nice work. It returns empty string or null if everything is OK ?

**Comment by tarioch** [comment]
Unfortunately it's not 100% nice but I didn't want to change any of the protactor code.

If you look in the clientsidescripts, there's a couple of cases where the callback is called in error cases, especially in the angularjs cases it unfortunately doesn't return a good error. In the angular2+ cases it's a bit better as there mostly it returns the error message.

**Comment by paul-hammant** [comment]
Hmm, my build is failing on my mac. I don't think it's your contrib. Does it pass for you?

e.g.

```
Failed tests:   basic_actions(com.paulhammant.ngwebdriver.AngularAndWebDriverTest): move target out of bounds(..)
```

**Comment by tarioch** [comment]
No, unfortunately most of the other tests didn't pass for me either, I was thinking it had something to do with my setup. I just made sure that the test case I added was working.

**Comment by paul-hammant** [comment]
Try doing a git-pull I commented out a bunch as "angularjshub is down". Another day, I can get them back from the way-back-machine (they work there but are super slow), and copy them into the localhost JettyServer test thingy.

**Comment by paul-hammant** [comment]
OK, so the tests pass on a macMini but not on my MacBookAir with the same everything :(

**Comment by paul-hammant** [comment]
v1.1.5 released .... CHANGES.txt updated to reflect changes.

**Pull request merged**
