### PR TITLE
updating release / dependency info and a slightly more concrete example of waiting

### PR DESCRIPTION
**Pull request by symonk**
updated maven documentation, release information details and added a slightly more concrete example of waiting for angular to encompass full driver setup

### CODE REVIEW

**Comment by paul-hammant** [comment]
Two things:

1) As a person who's spend their entire Java life railing against ServiceLocator (https://paulhammant.com/files/JDJ_2003_12_IoC_Rocks.pdf) I'm not going to see it sneak into a tech that I'm leading. Ref: ChromeDriverManager.getInstance().setup()

2) Moving the versions to properties. Does the dependencies:analyze thing still work after that? Or is it versions:analyze I can't remember.

- Paul

**Comment by dantran** [comment]
sorry about stealing this thread.  is waitForAngularRequestsToFinish() a one time deal?

**Comment by paul-hammant** [comment]
New issue please, @dantran

**Comment by symonk** [comment]
Hi @paul-hammant, sorry I’m not at home right now, apologies on the driver manager I was not aware about that / stance. Will update once I’m back home

**Pull request closed without merging**
